(function(){
var KEY='ares_speaking_v4', state={turns:0,minutes:0,streak:0,lastDay:'',mistakes:[]};try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)Object.assign(state,x)}catch(e){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function el(id){return document.getElementById(id)}function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function apiKey(){return localStorage.getItem('ing_defter_api_key')||localStorage.getItem('ing_defter_api_key_local_backup')||''}
function setKey(){var v=prompt('Gemini API anahtarını gir:',apiKey());if(v){localStorage.setItem('ing_defter_api_key',v.trim());localStorage.setItem('ing_defter_api_key_local_backup',v.trim());alert('API anahtarı kaydedildi.')}}
function touch(){state.turns++;state.minutes+=1;var t=new Date().toISOString().slice(0,10);if(state.lastDay!==t){var d=new Date();d.setDate(d.getDate()-1);var y=d.toISOString().slice(0,10);state.streak=state.lastDay===y?state.streak+1:1;state.lastDay=t}save();progress()}
function progress(){if(el('pTurns'))el('pTurns').textContent=state.turns;if(el('pMinutes'))el('pMinutes').textContent=Math.round(state.minutes);if(el('pStreak'))el('pStreak').textContent=state.streak;if(el('pMistakes'))el('pMistakes').textContent=state.mistakes.length;var box=el('mistakeList');if(box){box.innerHTML=state.mistakes.length?state.mistakes.map(function(m){return '<div style="padding:10px 0;border-bottom:1px solid #ddd"><b>Sen:</b> '+esc(m.a)+'<br><b>Daha doğal:</b> '+esc(m.b)+'</div>'}).join(''):'Henüz önemli bir hata kaydedilmedi.'}}
async function ask(system,user){var key=apiKey();if(!key){setKey();key=apiKey();if(!key)throw new Error('API anahtarı yok');}var url='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';var r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:user}]}],generationConfig:{maxOutputTokens:500,temperature:.7}})});if(!r.ok)throw new Error('AI bağlantısı kurulamadı');var d=await r.json();var parts=((((d.candidates||[])[0]||{}).content||{}).parts||[]);return parts.map(function(p){return p.text||''}).join('').trim()}
function feedback(id,text){if(el(id))el(id).innerHTML='<div class="feedback">'+esc(text)+'</div>'}
function voice(target){var R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Bu tarayıcıda ses tanıma kullanılamıyor. Yazıp gönderebilirsin.');return}var box=el(target);var r=new R();r.lang='en-US';r.interimResults=true;r.continuous=false;r.onresult=function(e){var t='';for(var i=0;i<e.results.length;i++)t+=e.results[i][0].transcript+' ';box.value=t.trim()};r.start()}
var quick=['What did you do after work yesterday?','What makes a café good for you?','What was the best part of your last trip?','What do you do when you cannot find the right English word?','Would you rather travel alone or with friends? Why?','How do you relax after a stressful day?'];
var surprise=['Your hotel room is noisy. Call reception and ask for another room.','You missed your train. Ask a station employee what your options are.','A tourist asks what food they should try in Türkiye. Recommend something.','Someone asks why you are learning English. Answer naturally.','Your flight has been delayed. Ask airline staff about your options.'];
var scenarios={passport:['London · Immigration officer','What is the purpose of your visit and how long will you stay?'],hotel:['Rome · Receptionist','Your reservation cannot be found. Explain the situation.'],restaurant:['Barcelona · Waiter','You received the wrong meal. Explain politely.'],train:['Prague · Station employee','You missed your connection. Ask for the next option.'],directions:['Prague · Local resident','Your phone battery is dead. Ask for directions to the old town.'],shopping:['Milan · Shop assistant','Return a shirt because it is the wrong size.'],social:['Dublin · Traveller','Someone starts small talk with you. Keep the conversation going.']};
function drawScenario(){var s=scenarios[el('abroadSelect').value];el('abroadScenario').innerHTML='<div class="tiny">'+s[0]+'</div><div class="prompt">'+s[1]+'</div>'}
document.addEventListener('click',function(e){var v=e.target.getAttribute&&e.target.getAttribute('data-voice');if(v)voice(v);var r=e.target.getAttribute&&e.target.getAttribute('data-role');if(r){var a=r.split('|'),txt=el(a[2]).value.trim();if(!txt)return;touch();feedback(a[3],'Karşı taraf düşünüyor…');ask('You are '+a[0]+'. Situation: '+a[1]+' Stay in character. Reply in short realistic B1 English and ask one follow-up question.',txt).then(function(z){feedback(a[3],z)}).catch(function(err){feedback(a[3],err.message)})}});
el('apiBtn').onclick=setKey;el('coachSend').onclick=function(){var t=el('coachText').value.trim();if(!t)return;var c=el('coachChat');c.innerHTML+='<div class="msg me">'+esc(t)+'</div>';touch();ask('You are Ares, a speaking-first coach for an A2-B1 Turkish learner. Keep the learner speaking. Ignore tiny errors. Correct at most one important error briefly, then ask exactly one natural follow-up question. Short English response.',t).then(function(z){c.innerHTML+='<div class="msg ai">'+esc(z)+'</div>';c.scrollTop=c.scrollHeight}).catch(function(err){feedback('coachFeedback',err.message)})};
el('quickNew').onclick=function(){el('quickQ').textContent=quick[Math.floor(Math.random()*quick.length)]};el('quickEval').onclick=function(){var t=el('quickText').value.trim();if(!t)return;touch();ask('Evaluate this A2-B1 spoken answer. Fluency first. In Turkish give: Anlaşılırlık, one natural English version, and one next question. Ignore tiny errors.',el('quickQ').textContent+'\nAnswer: '+t).then(function(z){feedback('quickFeedback',z)}).catch(function(e){feedback('quickFeedback',e.message)})};
el('surpriseNew').onclick=function(){el('surpriseQ').textContent=surprise[Math.floor(Math.random()*surprise.length)]};el('surpriseEval').onclick=function(){var t=el('surpriseText').value.trim();if(!t)return;touch();ask('Evaluate this spontaneous A2-B1 answer. Fluency first. Turkish concise feedback and one natural version.',el('surpriseQ').textContent+'\nAnswer: '+t).then(function(z){feedback('surpriseFeedback',z)}).catch(function(e){feedback('surpriseFeedback',e.message)})};
el('abroadSelect').onchange=drawScenario;el('abroadSend').onclick=function(){var s=scenarios[el('abroadSelect').value],t=el('abroadText').value.trim();if(!t)return;touch();feedback('abroadFeedback','Karşı taraf düşünüyor…');ask('Role-play as '+s[0]+'. Situation: '+s[1]+'. Stay in character, reply in short realistic B1 English, ask one follow-up question.',t).then(function(z){feedback('abroadFeedback',z)}).catch(function(e){feedback('abroadFeedback',e.message)})};
var chunks=['Let me think…','I see your point, but…','To be honest…','What I mean is…','It depends on…','As far as I know…'];el('dailyChunk').textContent=chunks[Math.floor(Date.now()/86400000)%chunks.length];drawScenario();progress();if(!location.hash)location.hash='mission';
})();
